export enum AccountType {
  USER_WALLET = "USER_WALLET",
  MERCHANT_REVENUE = "MERCHANT_REVENUE",
  SYSTEM_EXTERNAL_SOURCE = "SYSTEM_EXTERNAL_SOURCE",
  SYSTEM_EXERNAL_SINK = "SYSTEM_EXERNAL_SINK",
  SYSTEM_FEES = "SYSTEM_FEES"
}

export enum AccountStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE"
}